/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package business.EmployerDirectory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import ui.DatabaseConnection;
/**
 *
 * @author Atharv Joshi
 */
public class JobCreatedJPanel extends javax.swing.JPanel {

    private String username;

    /**
     * Creates new form JobCreatedJPanel
     */
    public JobCreatedJPanel(String username) {
        initComponents();
        this.username = username;
        populateJobsTable();
    }

    
    private void populateJobsTable() {
        // Clear existing data in the table
        DefaultTableModel model = (DefaultTableModel) tblJobs.getModel();
        model.setRowCount(0);

        // Fetch EmployerID based on the username
        int employerID = getEmployerID(username);

        // Fetch jobs based on the obtained EmployerID
        String sql = "SELECT JobID, JobType, JobCategory, JobDescription, ApplicationDate FROM jobs WHERE EmployerID = ?";
        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setInt(1, employerID);
            ResultSet resultSet = preparedStatement.executeQuery();

            // Populate the tblJobs table with data from the jobs table
            while (resultSet.next()) {
                Object[] rowData = {
                        resultSet.getInt("JobID"),
                        resultSet.getString("JobType"),
                        resultSet.getString("JobCategory"),
                        resultSet.getString("JobDescription"),
                        resultSet.getTimestamp("ApplicationDate")
                };
                model.addRow(rowData);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private int getEmployerID(String username) {
        int employerID = -1;

        String sql = "SELECT EmployerID FROM employers WHERE Username = ?";

        try (Connection connection = DatabaseConnection.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setString(1, username);
            ResultSet resultSet = preparedStatement.executeQuery();

            if (resultSet.next()) {
                employerID = resultSet.getInt("EmployerID");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return employerID;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJobs = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        tblJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "JobID", "JobType", "JobCategory", "JobDescription", "ApplicationDate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJobs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJobs;
    // End of variables declaration//GEN-END:variables
}
