/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package business.StudentDirectory;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

import ui.DatabaseConnection;

/**
 *
 * @author Atharv Joshi
 */
public class StuProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StuProfileJPanel
     * @param username
     */
    private String username;
    public StuProfileJPanel(String username) {
        initComponents();
        this.username = username;
        fetchUserInfo(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        txtdob = new javax.swing.JTextField();
        txtenrollstat = new javax.swing.JTextField();
        txtstuid = new javax.swing.JTextField();
        txtnation = new javax.swing.JTextField();
        txtemergency = new javax.swing.JTextField();
        txtcredit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Contact Number");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Gender");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 130, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Date Of Birth");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Emergency Contact");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 130, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Enrollmenent Status");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 130, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Student ID");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 130, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Nationality");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 130, 40));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Credits Earned");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 130, 40));

        txtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactActionPerformed(evt);
            }
        });
        add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 200, 40));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 200, 40));
        add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, 40));
        add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 200, 40));
        add(txtenrollstat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 200, 40));
        add(txtstuid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 200, 40));
        add(txtnation, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 200, 40));

        txtemergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemergencyActionPerformed(evt);
            }
        });
        add(txtemergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 200, 40));
        add(txtcredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Profile  Dashboard");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 334, 42));
    }// </editor-fold>//GEN-END:initComponents

    private void txtemergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemergencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemergencyActionPerformed

    private void txtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtcredit;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemergency;
    private javax.swing.JTextField txtenrollstat;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnation;
    private javax.swing.JTextField txtstuid;
    // End of variables declaration//GEN-END:variables

    private void fetchUserInfo(String username) {
        // Database connection parameters
      
       try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DatabaseConnection.getConnection();

            String query = "SELECT * FROM students WHERE username = ?";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, username);
                try (ResultSet resultSet = preparedStatement.executeQuery()) {
                    if (resultSet.next()) {
                        // Populate the UI components with user information
                        txtname.setText(resultSet.getString("Name"));
                        txtcontact.setText(resultSet.getString("Contact"));
                        txtdob.setText(resultSet.getString("DOB"));
                        txtgender.setText(resultSet.getString("Gender"));
                        txtnation.setText(resultSet.getString("Nationality"));
                        txtstuid.setText(resultSet.getString("StudentID"));
                        txtenrollstat.setText(resultSet.getString("EnrollmentStatus"));
                        txtemergency.setText(resultSet.getString("EmergencyContact"));
                        txtcredit.setText(resultSet.getString("CreditsEarned"));
                                                // You can also handle the profile photo here if it's stored in the database.
                    } else {
                        // Handle the case when no user is found with the given username
                        // For example: show an error message or clear the fields.
                        // For now, let's clear the fields
                    }
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            // Handle exceptions (e.g., show an error message).
            ex.printStackTrace();
        }
    }
    }
