/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package business.FacultyDirectory;


import business.CafeEndUsers.EndUsers;

import java.awt.Dimension;
import java.awt.FlowLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Atharva
 */
public class FacultyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyJPanel
     */

    private String username; 
    public FacultyJPanel(String username) {
        initComponents(); // Initialize components here
        this.username = username;
        add(lblusername); // Add lblusername to the panel
    }
    public void setUsername(String username) {
        lblusername.setText(username);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        btnFacultyProfile = new javax.swing.JButton();
        btnCourseDetails = new javax.swing.JButton();
        btnstudentlist = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        btnAddCourse = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        btnLibrary = new javax.swing.JButton();
        btnCafe = new javax.swing.JButton();
        btnItSupport = new javax.swing.JButton();

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnFacultyProfile.setBackground(new java.awt.Color(51, 51, 255));
        btnFacultyProfile.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnFacultyProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnFacultyProfile.setText("My Profile");
        btnFacultyProfile.setBorder(null);
        btnFacultyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyProfileActionPerformed(evt);
            }
        });

        btnCourseDetails.setBackground(new java.awt.Color(51, 51, 255));
        btnCourseDetails.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnCourseDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnCourseDetails.setText("Course Details");
        btnCourseDetails.setBorder(null);
        btnCourseDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseDetailsActionPerformed(evt);
            }
        });

        btnstudentlist.setBackground(new java.awt.Color(51, 51, 255));
        btnstudentlist.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnstudentlist.setForeground(new java.awt.Color(255, 255, 255));
        btnstudentlist.setText("Students List");
        btnstudentlist.setBorder(null);
        btnstudentlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstudentlistActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WELCOME");

        lblusername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAddCourse.setBackground(new java.awt.Color(51, 51, 255));
        btnAddCourse.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setText("Add Course");
        btnAddCourse.setBorder(null);
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 255));
        jButton5.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });


        btnLibrary.setBackground(new java.awt.Color(51, 51, 255));
        btnLibrary.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnLibrary.setText("Library");
        btnLibrary.setBorder(null);
        btnLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryActionPerformed(evt);
            }
        });

        btnCafe.setBackground(new java.awt.Color(51, 51, 255));
        btnCafe.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnCafe.setForeground(new java.awt.Color(255, 255, 255));
        btnCafe.setText("Cafeteria");
        btnCafe.setBorder(null);
        btnCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCafeActionPerformed(evt);
            }
        });

        btnItSupport.setBackground(new java.awt.Color(51, 51, 255));
        btnItSupport.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnItSupport.setForeground(new java.awt.Color(255, 255, 255));
        btnItSupport.setText("IT Support");
        btnItSupport.setBorder(null);
        btnItSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItSupportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacultyProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCourseDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnstudentlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

                        .addContainerGap())
                    .addComponent(btnItSupport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLibrary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCafe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnFacultyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCourseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnstudentlist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnItSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FACULTY PORTAL");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(573, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacultyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyProfileActionPerformed
        // TODO add your handling code here:

        FacultyProfileJPanel facultyProfile = new FacultyProfileJPanel(username);
        splitPane.setRightComponent(facultyProfile);
    }//GEN-LAST:event_btnFacultyProfileActionPerformed

    private void btnCourseDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseDetailsActionPerformed
        // TODO add your handling code ????????????????????????? = new CoursesTaughtJPanel();
        CoursesTaughtJPanel Coursestaughtpanel = new CoursesTaughtJPanel(username);
        splitPane.setRightComponent(Coursestaughtpanel);
    }//GEN-LAST:event_btnCourseDetailsActionPerformed

    private void btnstudentlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstudentlistActionPerformed
        // TODO add your handling code here:
        StudentListJPanel Studentlistpanel = new StudentListJPanel(username);
        splitPane.setRightComponent(Studentlistpanel);
        
    }//GEN-LAST:event_btnstudentlistActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
        FacultyAddJPanel addcoursepanel = new FacultyAddJPanel(username);
        splitPane.setRightComponent(addcoursepanel);
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        currentFrame.dispose();
        FacultyLoginFrame loginFrame = new FacultyLoginFrame();
        loginFrame.setSize(new Dimension(1140, 600));
        loginFrame.setLocationRelativeTo(null);
        // Set the new login frame visible and dispose the current frame
        loginFrame.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibraryActionPerformed

    private void btnCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCafeActionPerformed
        // TODO add your handling code here:
        EndUsers endusercafe = new EndUsers(username);
        splitPane.setRightComponent(endusercafe);
    }//GEN-LAST:event_btnCafeActionPerformed

    private void btnItSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItSupportActionPerformed
        // TODO add your handling code here:
//        StuReputationIndexJPanel reputationindex = new StuReputationIndexJPanel();
//        splitPane.setRightComponent(reputationindex);
    }//GEN-LAST:event_btnItSupportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnCafe;
    private javax.swing.JButton btnCourseDetails;
    private javax.swing.JButton btnFacultyProfile;
    private javax.swing.JButton btnItSupport;
    private javax.swing.JButton btnLibrary;
    private javax.swing.JButton btnstudentlist;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblusername;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
