/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package business.CafeOrgDirectory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import ui.DatabaseConnection;

/**
 *
 * @author Atharv Joshi
 */
public class ManagerProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerProfileJPanel
     */
    public ManagerProfileJPanel() {
        initComponents();
        fetchUserInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtEmployeeID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDateOfHire = new javax.swing.JTextField();
        txtContract = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Position");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Full Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Employee ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 130, 30));

        txtposition.setForeground(new java.awt.Color(0, 0, 0));
        txtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositionActionPerformed(evt);
            }
        });
        add(txtposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 200, 40));

        txtname.setForeground(new java.awt.Color(0, 0, 0));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 200, 40));

        txtEmployeeID.setForeground(new java.awt.Color(0, 0, 0));
        add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 200, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Profile  Dashboard");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 334, 42));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Phone");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 130, 40));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Email");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Address");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 130, 30));

        txtPhone.setForeground(new java.awt.Color(0, 0, 0));
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, 40));

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 200, 40));

        txtAddress.setForeground(new java.awt.Color(0, 0, 0));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 200, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Date of Hire");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 130, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Contract Type");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 130, 30));

        txtDateOfHire.setForeground(new java.awt.Color(0, 0, 0));
        txtDateOfHire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfHireActionPerformed(evt);
            }
        });
        add(txtDateOfHire, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 200, 40));

        txtContract.setForeground(new java.awt.Color(0, 0, 0));
        add(txtContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 200, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositionActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtDateOfHireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfHireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfHireActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContract;
    private javax.swing.JTextField txtDateOfHire;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtposition;
    // End of variables declaration//GEN-END:variables

// Assuming you have a Statement object named stmt

        private void fetchUserInfo() {
        // Database connection parameters
      
       try {
            Connection connection = DatabaseConnection.getConnection();

            String query = "SELECT * FROM campus_dining_staff  WHERE Position = 'Cafeteria Manager'";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                
                try (ResultSet rs = preparedStatement.executeQuery()) {
                    if (rs.next()) {
                        // Populate the UI components with user information
                        txtname.setText(rs.getString("Name"));
                        txtposition.setText(rs.getString("Position"));
                        txtEmployeeID.setText(String.valueOf(rs.getInt("EmployeeID")));
                        txtPhone.setText(rs.getString("Phone"));
                        txtEmail.setText(rs.getString("Email"));
                        txtAddress.setText(rs.getString("Address"));
                        txtDateOfHire.setText(rs.getString("DateOfHire"));
                        txtContract.setText(rs.getString("ContractType"));
                                                // You can also handle the profile photo here if it's stored in the database.
                    } else {
                        // Handle the case when no user is found with the given username
                        // For example: show an error message or clear the fields.
                        // For now, let's clear the fields
                    }
                }
            }
        } catch (SQLException ex) {
            // Handle exceptions (e.g., show an error message).
            ex.printStackTrace();
        }
    }
}