/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package business.LibraryEndUser;

/**
 *
 * @author Atharva
 */
public class LibraryEndUser extends javax.swing.JPanel {

    /**
     * Creates new form LibraryEndUser
     */
    public LibraryEndUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblallbooks = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        btnBorowBook = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblallmenu1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library");

        tblallbooks.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblallbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "BookID ", "Title", "Author", "Genre", "Available Quantity", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblallbooks);

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Borrow book");

        jLabel10.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel10.setText("ID");

        btnBorowBook.setBackground(new java.awt.Color(51, 51, 255));
        btnBorowBook.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btnBorowBook.setForeground(new java.awt.Color(255, 255, 255));
        btnBorowBook.setText("Borrow");
        btnBorowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorowBookActionPerformed(evt);
            }
        });

        tblallmenu1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tblallmenu1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "BookID", "Return Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblallmenu1);

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Your Books");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBorowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBorowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorowBookActionPerformed
        // TODO add your handling code here:
        //        String courseID = txtCourseID.getText();
        //        String courseName = txtCourseName.getText();
        //        String description = txtCourseDescription.getText();
        //        int credits = Integer.parseInt(jTextField5.getText());
        //        int maxStudents = Integer.parseInt(jTextField6.getText());
        //        String schedule = jTextField7.getText();
        //        String employeeID = getEmployeeIDFromUsername(username);
        //
        //        // Check if the employee already has 2 courses
        //        if (getNumberOfCoursesForEmployee(employeeID) >= 2) {
            //            JOptionPane.showMessageDialog(this, "Error: The employee already has 2 courses.", "Error", JOptionPane.ERROR_MESSAGE);
            //            return;
            //        }
        //
        //        // Check if the CourseID already exists
        //        if (isCourseIDExists(courseID)) {
            //            JOptionPane.showMessageDialog(this, "Error: Course with the same ID already exists.", "Error", JOptionPane.ERROR_MESSAGE);
            //            return;
            //        }
        //
        //        // Perform the insertion of the new course into the database
        //        try {
            //            String insertQuery = "INSERT INTO courses (CourseID, CourseName, Description, Credits, EmployeeID, MaximumStudents, Schedule) VALUES (?, ?, ?, ?, ?, ?, ?)";
            //            PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
            //            preparedStatement.setString(1, courseID);
            //            preparedStatement.setString(2, courseName);
            //            preparedStatement.setString(3, description);
            //            preparedStatement.setInt(4, credits);
            //            preparedStatement.setString(5, employeeID);
            //            preparedStatement.setInt(6, maxStudents);
            //            preparedStatement.setString(7, schedule);
            //
            //            int rowsAffected = preparedStatement.executeUpdate();
            //            if (rowsAffected > 0) {
                //                JOptionPane.showMessageDialog(this, "Course added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                //            } else {
                //                JOptionPane.showMessageDialog(this, "Error: Failed to add the course.", "Error", JOptionPane.ERROR_MESSAGE);
                //            }
            //        } catch (SQLException e) {
            //            e.printStackTrace();
            //            JOptionPane.showMessageDialog(this, "Error: Failed to add the course. Please check the console for details.", "Error", JOptionPane.ERROR_MESSAGE);
            //        }
        //
        //        // Reset text fields after successful addition
        //        txtCourseID.setText("");
        //        txtCourseName.setText("");
        //        txtCourseDescription.setText("");
        //        jTextField5.setText("");
        //        jTextField6.setText("");
        //        jTextField7.setText("");
    }//GEN-LAST:event_btnBorowBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorowBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable tblallbooks;
    private javax.swing.JTable tblallmenu1;
    // End of variables declaration//GEN-END:variables
}
